#!/usr/bin/env python3
"""Step 15b3 — targeted downstream rerun for corrected hPDI.

READ-ONLY / ISOLATED.
This script does NOT modify canonical Diet→Microbiome or Diet→CGM outputs.
It reruns only the hPDI branch with the corrected hPDI score generated by
Step 15b2, while preserving the original cohort, covariate flags, model
definitions and multiple-testing families.

Scope
-----
A) Corrected hPDI → microbiome
   - Model0
   - Model2
   - Model3
   - FDR across 379 species, exactly as canonical hPDI MWAS.

B) Corrected hPDI → CGM
   - Model0
   - Model2
   - Model3
   - 3 outcomes.
   - To preserve the canonical 12-test BH family, the corrected 3 hPDI
     p-values replace the old hPDI rows while the other 9 canonical rows
     remain unchanged; BH is then recomputed across all 12.

C) Old-vs-corrected comparison
   - N
   - significant counts
   - retained/lost/gained
   - beta Spearman rho
   - beta sign flips
   - hPDI × glucose_cv Model3 gate status.

No bridge or mediation is rerun here. Those are only rerun if this targeted
association audit shows the corrected hPDI gate remains eligible.

Outputs
-------
diet_microbiome_glucose_analysis/outputs/reports/new_diet_extension/
    hpdi_correction_audit/downstream/
        microbiome/
        cgm/
        15b3_hpdi_mwas_comparison_summary.csv
        15b3_hpdi_cgm_comparison_summary.csv
        15b3_corrected_hpdi_downstream_summary.txt
"""

from __future__ import annotations

from pathlib import Path
import importlib.util
import sys
import numpy as np
import pandas as pd
from scipy.stats import t as t_dist


ROOT = Path("/home/ec2-user/Desktop/HPP/Data")

DM_ANALYSIS = ROOT / "diet_microbiome_analysis"
DG_ANALYSIS = ROOT / "diet_microbiome_glucose_analysis"

ALIGNED_DIET = DM_ANALYSIS / "data" / "00_aligned_four_scores.csv"
ALIGNED_MICRO = DM_ANALYSIS / "data" / "00_aligned_species_clr_zscore.csv"
COV_MASTER = ROOT / "co-variant" / "outputs" / "data" / "02_covariate_master.csv"

FORMAL_CGM = (
    DG_ANALYSIS / "outputs" / "data" / "00_current4_diet_cgm_cohort.csv"
)

CORRECTED_HPDI = (
    DG_ANALYSIS / "outputs" / "reports" / "new_diet_extension"
    / "hpdi_correction_audit" / "corrected_scores"
    / "hpdi_participant_scores.csv"
)
CORRECTED_Z_COL = "hpdi_score_energy_adjusted_z"

MWAS_COMMON_PATH = (
    DM_ANALYSIS / "scripts" / "mwas_adjusted_common.py"
)
CGM_COMMON_PATH = (
    DG_ANALYSIS / "scripts" / "cgm_models_current4_common.py"
)

OLD_MWAS = {
    0: DM_ANALYSIS / "reports" / "03_MWAS_hPDI_model0.csv",
    2: DM_ANALYSIS / "reports" / "04_MWAS_hPDI_model2.csv",
    3: DM_ANALYSIS / "reports" / "05_MWAS_hPDI_model3.csv",
}
OLD_CGM = {
    0: DG_ANALYSIS / "outputs" / "models" / "01_current4_diet_cgm_model0.csv",
    2: DG_ANALYSIS / "outputs" / "models" / "02_current4_diet_cgm_model2.csv",
    3: DG_ANALYSIS / "outputs" / "models" / "03_current4_diet_cgm_model3_bmi.csv",
}

OUT = (
    DG_ANALYSIS / "outputs" / "reports" / "new_diet_extension"
    / "hpdi_correction_audit" / "downstream"
)
MWAS_OUT = OUT / "microbiome"
CGM_OUT = OUT / "cgm"

MWAS_SUMMARY = OUT / "15b3_hpdi_mwas_comparison_summary.csv"
CGM_SUMMARY = OUT / "15b3_hpdi_cgm_comparison_summary.csv"
SUMMARY = OUT / "15b3_corrected_hpdi_downstream_summary.txt"

META_COLS = ["participant_id", "cohort", "research_stage", "array_index"]
PRIMARY_OUTCOMES = {
    "mean_glucose": "cgm_mean_z",
    "glucose_cv": "cgm_cv_z",
    "time_above_140": "cgm_above_140_z",
}


def require(path: Path, label: str) -> None:
    if not path.is_file():
        raise FileNotFoundError(f"{label} missing: {path}")


def norm_id(s: pd.Series) -> pd.Series:
    return s.astype(str).str.strip().str.replace(r"\.0$", "", regex=True)


def to_bool(s: pd.Series) -> pd.Series:
    if pd.api.types.is_bool_dtype(s):
        return s.fillna(False).astype(bool)
    x = s.astype(str).str.strip().str.lower()
    mapping = {
        "true": True, "1": True, "1.0": True,
        "false": False, "0": False, "0.0": False,
        "nan": False, "none": False, "": False,
    }
    bad = sorted(set(x.unique()) - set(mapping))
    if bad:
        raise RuntimeError(f"Unexpected boolean values: {bad[:20]}")
    return x.map(mapping).astype(bool)


def bh_fdr(pvalues) -> np.ndarray:
    p = np.asarray(pvalues, dtype=float)
    if not np.isfinite(p).all():
        raise RuntimeError("BH-FDR received non-finite p-values")
    n = len(p)
    order = np.argsort(p)
    ranked = p[order]
    q = ranked * n / np.arange(1, n + 1)
    q = np.minimum.accumulate(q[::-1])[::-1]
    out = np.empty_like(q)
    out[order] = np.clip(q, 0, 1)
    return out


def load_module(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not load module: {path}")
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


def spearman(x: pd.Series, y: pd.Series) -> float:
    a = pd.to_numeric(x, errors="coerce")
    b = pd.to_numeric(y, errors="coerce")
    ok = a.notna() & b.notna() & np.isfinite(a) & np.isfinite(b)
    if int(ok.sum()) < 3:
        return np.nan
    return float(
        a.loc[ok].rank(method="average").corr(
            b.loc[ok].rank(method="average"), method="pearson"
        )
    )


def corrected_score_table() -> pd.DataFrame:
    d = pd.read_csv(
        CORRECTED_HPDI,
        usecols=["participant_id", CORRECTED_Z_COL],
        low_memory=False,
    )
    d["participant_id"] = norm_id(d["participant_id"])
    if d["participant_id"].duplicated().any():
        raise RuntimeError("Corrected hPDI score has duplicate participant_id")
    d = d.rename(columns={CORRECTED_Z_COL: "hPDI_z_corrected"})
    return d


def fit_univariate_ols(x, Y):
    x = np.asarray(x, dtype=np.float64)
    Y = np.asarray(Y, dtype=np.float64)
    xc = x - x.mean()
    Y_mean = Y.mean(axis=0)
    Yc = Y - Y_mean
    sxx = np.sum(xc ** 2)
    if sxx <= 0:
        raise RuntimeError("Corrected hPDI has zero variance")
    beta = (xc[:, None] * Yc).sum(axis=0) / sxx
    intercept = Y_mean - beta * x.mean()
    resid = Y - (intercept[None, :] + x[:, None] * beta[None, :])
    n = len(x)
    df = n - 2
    sse = np.sum(resid ** 2, axis=0)
    mse = sse / df
    se = np.sqrt(mse / sxx)
    t_stat = beta / se
    p = 2 * t_dist.sf(np.abs(t_stat), df=df)
    sst = np.sum(Yc ** 2, axis=0)
    r2 = 1 - sse / sst
    tcrit = t_dist.ppf(.975, df=df)
    return beta, se, t_stat, p, r2, beta - tcrit * se, beta + tcrit * se, df


def prepare_microbiome_inputs():
    diet = pd.read_csv(ALIGNED_DIET, low_memory=False)
    micro = pd.read_csv(ALIGNED_MICRO, low_memory=False)
    corr = corrected_score_table()

    for label, d in [("aligned diet", diet), ("aligned microbiome", micro)]:
        d["participant_id"] = norm_id(d["participant_id"])
        if d["participant_id"].duplicated().any():
            raise RuntimeError(f"{label} has duplicate participant IDs")

    if diet["participant_id"].tolist() != micro["participant_id"].tolist():
        raise RuntimeError("Canonical aligned diet/microbiome participant order differs")

    old_ids = set(diet["participant_id"])
    corr_ids = set(corr["participant_id"])
    missing = old_ids - corr_ids
    if missing:
        raise RuntimeError(
            f"Corrected hPDI is missing {len(missing)} canonical aligned participants"
        )

    diet = diet.merge(corr, on="participant_id", how="left", validate="one_to_one")
    if diet["hPDI_z_corrected"].isna().any():
        raise RuntimeError("Corrected hPDI missing inside canonical aligned microbiome cohort")

    species = [c for c in micro.columns if c not in META_COLS]
    Y = micro[species].apply(pd.to_numeric, errors="coerce").to_numpy(float)
    if not np.isfinite(Y).all():
        raise RuntimeError("Microbiome matrix contains NaN/Inf")
    return diet, micro, species, Y


def run_mwas_model0(diet, species, Y):
    x = pd.to_numeric(diet["hPDI_z_corrected"], errors="coerce")
    valid = x.notna() & np.isfinite(x.to_numpy(float))
    idx = np.flatnonzero(valid.to_numpy())
    x_use = x.loc[valid].to_numpy(float)
    Y_use = Y[idx]

    beta, se, t, p, r2, lo, hi, df = fit_univariate_ols(x_use, Y_use)
    fdr = bh_fdr(p)
    out = pd.DataFrame({
        "score": "hPDI",
        "species": species,
        "N": len(x_use),
        "model": 0,
        "beta": beta,
        "SE": se,
        "t": t,
        "p": p,
        "FDR": fdr,
        "R2_full_model": r2,
        "CI_lower": lo,
        "CI_upper": hi,
        "df_resid": df,
    })
    out["significant_FDR05"] = out["FDR"] < .05
    out["direction"] = np.where(out["beta"] > 0, "positive", "negative")
    return out


def run_mwas_adjusted(diet, species, Y, model, mwas_common):
    needed = {
        "participant_id",
        "age_years",
        "sleep_duration_hours_day",
        "physical_activity_met_h_week",
        "vitamin_use",
        "hormone_use",
        "sex",
        "education_level",
        "smoking_status",
        "alcohol_intake_g_day",
        "bmi",
        f"hpdi_microbiome_model{model}_covariates_complete",
    }
    master = pd.read_csv(
        COV_MASTER,
        usecols=lambda c: c in needed,
        low_memory=False,
    )
    master["participant_id"] = norm_id(master["participant_id"])
    if master["participant_id"].duplicated().any():
        raise RuntimeError("Covariate master duplicate participant IDs")
    missing = sorted(needed - set(master.columns))
    if missing:
        raise RuntimeError(f"Covariate master missing columns: {missing}")

    merged = diet.merge(master, on="participant_id", how="left", validate="one_to_one")
    score = pd.to_numeric(merged["hPDI_z_corrected"], errors="coerce")
    flag = to_bool(merged[f"hpdi_microbiome_model{model}_covariates_complete"])
    valid = flag & score.notna() & np.isfinite(score.to_numpy(float))
    selected = merged.loc[valid].copy()
    idx = np.flatnonzero(valid.to_numpy())
    Y_use = Y[idx]

    X, names, ptab, cond = mwas_common.build_design(
        selected, "hPDI", "hPDI_z_corrected", model
    )
    beta, se, t, p, r2, lo, hi, df = mwas_common.fit_all_species(X, Y_use)
    fdr = mwas_common.bh_fdr(p)
    out = pd.DataFrame({
        "score": "hPDI",
        "species": species,
        "N": len(selected),
        "model": model,
        "beta": beta,
        "SE": se,
        "t": t,
        "p": p,
        "FDR": fdr,
        "R2_full_model": r2,
        "CI_lower": lo,
        "CI_upper": hi,
        "df_resid": df,
        "n_parameters": X.shape[1],
        "design_condition_number": cond,
    })
    out["significant_FDR05"] = out["FDR"] < .05
    out["direction"] = np.where(out["beta"] > 0, "positive", "negative")
    return out


def bool_col(s: pd.Series) -> pd.Series:
    if pd.api.types.is_bool_dtype(s):
        return s.fillna(False)
    return (
        s.astype(str).str.strip().str.lower()
        .isin({"true", "1", "1.0", "yes"})
    )


def compare_mwas(model: int, new: pd.DataFrame) -> dict:
    old = pd.read_csv(OLD_MWAS[model], low_memory=False)
    req = {"species", "N", "beta", "FDR", "significant_FDR05"}
    missing = sorted(req - set(old.columns))
    if missing:
        raise RuntimeError(f"Old MWAS model{model} missing: {missing}")

    m = old[["species", "N", "beta", "FDR", "significant_FDR05"]].merge(
        new[["species", "N", "beta", "FDR", "significant_FDR05"]],
        on="species",
        suffixes=("_old", "_corrected"),
        how="inner",
        validate="one_to_one",
    )
    if len(m) != 379:
        raise RuntimeError(f"Expected 379 species in MWAS compare, got {len(m)}")

    old_sig = bool_col(m["significant_FDR05_old"])
    new_sig = bool_col(m["significant_FDR05_corrected"])
    signs = np.sign(pd.to_numeric(m["beta_old"])) != np.sign(
        pd.to_numeric(m["beta_corrected"])
    )

    comparison_path = MWAS_OUT / f"15b3_hPDI_model{model}_old_vs_corrected.csv"
    m.to_csv(comparison_path, index=False)

    return {
        "model": model,
        "old_N": int(pd.to_numeric(m["N_old"]).median()),
        "corrected_N": int(pd.to_numeric(m["N_corrected"]).median()),
        "old_significant_FDR05": int(old_sig.sum()),
        "corrected_significant_FDR05": int(new_sig.sum()),
        "retained_significant": int((old_sig & new_sig).sum()),
        "lost_significant": int((old_sig & ~new_sig).sum()),
        "gained_significant": int((~old_sig & new_sig).sum()),
        "beta_spearman_rho_all379": spearman(
            m["beta_old"], m["beta_corrected"]
        ),
        "beta_sign_flips_all379": int(signs.sum()),
        "same_sign_among_old_significant": int(
            (~signs & old_sig).sum()
        ),
    }


def prepare_cgm_cohort():
    cohort = pd.read_csv(FORMAL_CGM, low_memory=False)
    corr = corrected_score_table()
    cohort["participant_id"] = norm_id(cohort["participant_id"])
    if cohort["participant_id"].duplicated().any():
        raise RuntimeError("Formal Diet-CGM cohort duplicate participant IDs")
    cohort = cohort.merge(corr, on="participant_id", how="left", validate="one_to_one")
    if cohort["hPDI_z_corrected"].isna().any():
        # Only participants in formal Diet-CGM cohort should all be in corrected score table.
        n = int(cohort["hPDI_z_corrected"].isna().sum())
        raise RuntimeError(f"Corrected hPDI missing for {n} formal Diet-CGM participants")
    return cohort


def run_cgm_model(cohort, model: int, cgm_common):
    eligible = cgm_common.to_bool(cohort["primary_cgm_analysis_eligible"])
    score = pd.to_numeric(cohort["hPDI_z_corrected"], errors="coerce")

    if model == 0:
        complete = pd.Series(True, index=cohort.index)
        flag_col = "none"
    else:
        flag_col = f"hpdi_cgm_model{model}_covariates_complete"
        if flag_col not in cohort.columns:
            raise RuntimeError(f"Formal cohort missing {flag_col}")
        complete = cgm_common.to_bool(cohort[flag_col])

    rows = []
    for outcome_name, outcome_col in PRIMARY_OUTCOMES.items():
        y_num = pd.to_numeric(cohort[outcome_col], errors="coerce")
        valid = (
            eligible
            & complete
            & score.notna()
            & y_num.notna()
            & np.isfinite(score.to_numpy(float))
            & np.isfinite(y_num.to_numpy(float))
        )
        selected = cohort.loc[valid].copy()
        y = y_num.loc[valid].to_numpy(float)

        X, names, params, cond = cgm_common.build_design(
            selected, "hPDI", "hPDI_z_corrected", model
        )
        fit = cgm_common.fit_ols(X, y)
        rows.append({
            "diet_score": "hPDI",
            "exposure": "hPDI_z_corrected",
            "outcome_name": outcome_name,
            "outcome": outcome_col,
            "model": model,
            "N": len(selected),
            "complete_case_flag": flag_col,
            "n_parameters": X.shape[1],
            "df_resid": fit["df_resid"],
            "design_condition_number": cond,
            "beta_diet": float(fit["coef"][1]),
            "SE_diet": float(fit["se"][1]),
            "CI95_lower": float(fit["ci_lower"][1]),
            "CI95_upper": float(fit["ci_upper"][1]),
            "t_diet": float(fit["t"][1]),
            "p_value": float(fit["p"][1]),
            "R2_full_model": float(fit["r2"]),
        })
    return pd.DataFrame(rows)


def recompute_primary12_fdr(model: int, corrected_hpdi: pd.DataFrame):
    old = pd.read_csv(OLD_CGM[model], low_memory=False)
    if len(old) != 12:
        raise RuntimeError(f"Expected 12 canonical CGM rows model{model}, got {len(old)}")

    other = old.loc[~old["diet_score"].eq("hPDI")].copy()
    if len(other) != 9:
        raise RuntimeError(f"Expected 9 non-hPDI rows model{model}, got {len(other)}")

    # Ensure schemas line up on common result columns.
    common_cols = [c for c in old.columns if c in corrected_hpdi.columns]
    rebuilt = pd.concat(
        [
            other[common_cols],
            corrected_hpdi[common_cols],
        ],
        ignore_index=True,
    )
    if len(rebuilt) != 12:
        raise RuntimeError("Rebuilt primary12 family does not have 12 rows")

    rebuilt["FDR_BH_primary12"] = bh_fdr(rebuilt["p_value"].to_numpy())
    rebuilt["nominal_P05"] = rebuilt["p_value"] < .05
    rebuilt["FDR_primary12_05"] = rebuilt["FDR_BH_primary12"] < .05

    rebuilt["FDR_BH_within_score3"] = np.nan
    for score_name in ["AHEI", "AMED", "hPDI", "rEDIH"]:
        mask = rebuilt["diet_score"].eq(score_name)
        if int(mask.sum()) != 3:
            raise RuntimeError(
                f"Expected 3 outcomes for {score_name}, got {int(mask.sum())}"
            )
        rebuilt.loc[mask, "FDR_BH_within_score3"] = bh_fdr(
            rebuilt.loc[mask, "p_value"].to_numpy()
        )

    rebuilt.to_csv(
        CGM_OUT / f"15b3_primary12_model{model}_with_corrected_hPDI.csv",
        index=False,
    )
    return old, rebuilt


def compare_cgm(model: int, old: pd.DataFrame, rebuilt: pd.DataFrame) -> pd.DataFrame:
    old_h = old.loc[old["diet_score"].eq("hPDI")].copy()
    new_h = rebuilt.loc[rebuilt["diet_score"].eq("hPDI")].copy()

    cols = [
        "outcome_name", "N", "beta_diet", "p_value",
        "FDR_BH_primary12", "FDR_BH_within_score3",
    ]
    m = old_h[cols].merge(
        new_h[cols],
        on="outcome_name",
        suffixes=("_old", "_corrected"),
        validate="one_to_one",
    )
    m.insert(0, "model", model)
    m["beta_same_sign"] = (
        np.sign(pd.to_numeric(m["beta_diet_old"]))
        == np.sign(pd.to_numeric(m["beta_diet_corrected"]))
    )
    m["FDR_primary12_old_sig"] = pd.to_numeric(
        m["FDR_BH_primary12_old"]
    ).lt(.05)
    m["FDR_primary12_corrected_sig"] = pd.to_numeric(
        m["FDR_BH_primary12_corrected"]
    ).lt(.05)
    return m


def main() -> int:
    for path, label in [
        (ALIGNED_DIET, "canonical aligned diet"),
        (ALIGNED_MICRO, "canonical aligned microbiome"),
        (COV_MASTER, "covariate master"),
        (FORMAL_CGM, "formal Diet-CGM cohort"),
        (CORRECTED_HPDI, "corrected hPDI scores"),
        (MWAS_COMMON_PATH, "MWAS common module"),
        (CGM_COMMON_PATH, "CGM common module"),
        *[(p, f"old MWAS model{m}") for m, p in OLD_MWAS.items()],
        *[(p, f"old CGM model{m}") for m, p in OLD_CGM.items()],
    ]:
        require(path, label)

    MWAS_OUT.mkdir(parents=True, exist_ok=True)
    CGM_OUT.mkdir(parents=True, exist_ok=True)

    print("=== STEP 15b3 CORRECTED hPDI TARGETED DOWNSTREAM RERUN ===")
    print("CANONICAL_FILES_MODIFIED=False")
    print("OTHER_DIET_SCORES_REFIT=False")
    print("BRIDGE_MEDIATION_REFIT=False")

    mwas_common = load_module(MWAS_COMMON_PATH, "step15b3_mwas_common")
    cgm_common = load_module(CGM_COMMON_PATH, "step15b3_cgm_common")

    # -------------------- Microbiome branch --------------------
    diet, micro, species, Y = prepare_microbiome_inputs()

    new_mwas = {}
    new_mwas[0] = run_mwas_model0(diet, species, Y)
    new_mwas[2] = run_mwas_adjusted(diet, species, Y, 2, mwas_common)
    new_mwas[3] = run_mwas_adjusted(diet, species, Y, 3, mwas_common)

    mwas_rows = []
    for model, frame in new_mwas.items():
        frame.to_csv(
            MWAS_OUT / f"15b3_corrected_hPDI_MWAS_model{model}.csv",
            index=False,
        )
        mwas_rows.append(compare_mwas(model, frame))

    mwas_summary = pd.DataFrame(mwas_rows)
    mwas_summary.to_csv(MWAS_SUMMARY, index=False)

    # -------------------- CGM branch --------------------
    cohort = prepare_cgm_cohort()
    cgm_comparisons = []
    cgm_corrected_frames = {}

    for model in [0, 2, 3]:
        corrected = run_cgm_model(cohort, model, cgm_common)
        corrected.to_csv(
            CGM_OUT / f"15b3_corrected_hPDI_diet_cgm_model{model}.csv",
            index=False,
        )
        old, rebuilt = recompute_primary12_fdr(model, corrected)
        cgm_corrected_frames[model] = rebuilt
        cgm_comparisons.append(compare_cgm(model, old, rebuilt))

    cgm_summary = pd.concat(cgm_comparisons, ignore_index=True)
    cgm_summary.to_csv(CGM_SUMMARY, index=False)

    # -------------------- Gate / decision summary --------------------
    gate = cgm_summary.loc[
        cgm_summary["model"].eq(3)
        & cgm_summary["outcome_name"].eq("glucose_cv")
    ]
    if len(gate) != 1:
        raise RuntimeError("Could not uniquely identify Model3 hPDI glucose_cv gate row")
    gate = gate.iloc[0]

    m3 = mwas_summary.loc[mwas_summary["model"].eq(3)].iloc[0]

    lines = [
        "=== STEP 15b3 CORRECTED hPDI DOWNSTREAM SUMMARY ===",
        "CANONICAL_FILES_MODIFIED=False",
        "OTHER_DIET_SCORES_REFIT=False",
        "BRIDGE_MEDIATION_REFIT=False",
        "",
        "--- hPDI -> MICROBIOME OLD vs CORRECTED ---",
        mwas_summary.to_string(index=False),
        "",
        "--- hPDI -> CGM OLD vs CORRECTED ---",
        cgm_summary.to_string(index=False),
        "",
        "--- KEY GATE ---",
        f"MODEL3_HPDI_GLUCOSE_CV_OLD_BETA={gate['beta_diet_old']}",
        f"MODEL3_HPDI_GLUCOSE_CV_CORRECTED_BETA={gate['beta_diet_corrected']}",
        f"MODEL3_HPDI_GLUCOSE_CV_OLD_FDR12={gate['FDR_BH_primary12_old']}",
        f"MODEL3_HPDI_GLUCOSE_CV_CORRECTED_FDR12={gate['FDR_BH_primary12_corrected']}",
        f"MODEL3_HPDI_GLUCOSE_CV_GATE_RETAINED={bool(gate['FDR_primary12_corrected_sig'])}",
        "",
        "--- MODEL3 MICROBIOME STABILITY ---",
        f"OLD_SIG={int(m3['old_significant_FDR05'])}",
        f"CORRECTED_SIG={int(m3['corrected_significant_FDR05'])}",
        f"RETAINED_SIG={int(m3['retained_significant'])}",
        f"LOST_SIG={int(m3['lost_significant'])}",
        f"GAINED_SIG={int(m3['gained_significant'])}",
        f"BETA_RHO_ALL379={m3['beta_spearman_rho_all379']:.9f}",
        f"BETA_SIGN_FLIPS_ALL379={int(m3['beta_sign_flips_all379'])}",
        "",
        "NEXT_RULE:",
        "- If Model3 hPDI×glucose_cv FDR gate is retained and MWAS effect",
        "  directions/effect ranks remain highly stable, proceed to an isolated",
        "  corrected-hPDI bridge + mediation rerun.",
        "- If the gate is lost or MWAS changes materially, stop and reassess",
        "  the hPDI branch before integrating new diet indicators.",
        "",
        f"MWAS_SUMMARY={MWAS_SUMMARY}",
        f"CGM_SUMMARY={CGM_SUMMARY}",
    ]

    SUMMARY.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n" + "\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
